apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: luanti-data-pvc
  namespace: jeux
spec:
  storageClassName: "local-path"
  accessModes: 
    - ReadWriteOnce
  resources:
    storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: luanti
  namespace: jeux
  labels: 
    app: luanti
spec: 
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app: luanti
  template:
    metadata: 
      labels:
        app: luanti
    spec:
      volumes: 
        - name: luanti-data
          persistantVolumeClaim: luanti-data-pvc
      containers:
        - name: luanti
          image: lscr.io/linuxserver/luanti:latest
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: PUID
              values: "1000"
            - name: PGID
              values: "1000"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 30000
              protocol: UDP
          volumeMounts:
            - name: luanti-data
              mountPath: /config/.minetest
---
apiVersion: v1
kind: Service
metadata:
  name: luanti-svc
  namespace: jeux
spec:
  type: LoadBalancer
  ports:
    - name: luanti
      port: 30000
      targetPort: 30000
      protocol: UDP
  sellector:
    app: luanti