apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: luanti-data-pvc
  namespace: jeux
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: luanti
  namespace: jeux
  labels:
    app: luanti
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: luanti
  template:
    metadata:
      labels:
        app: luanti
    spec:
      volumes:
        - name: luanti-data
          persistentVolumeClaim:
            claimName: luanti-data-pvc
      initContainers:
        - name: luanti-git-clone
          image: alpine/git:2.49.0
          command:
            - sh
            - -c
            - | 
              [ -d /config/.minetest/games ] && echo "already present" || mkdir -p /config/.minetest/games
              GDIR=/config/.minetest/games
              echo "cleaning old worlds"
              rm -rf /config/.minetest/worlds/world
              echo "done"
              [ -d /config/.minetest/games/ctf ] && exit 0 
              git clone --recursive https://github.com/MT-CTF/capturetheflag /config/.minetest/games/ctf
              echo "coucou"
          volumeMounts:
            - name: luanti-data
              mountPath: /config/.minetest
      containers:
        - name: luanti
          image: lscr.io/linuxserver/luanti:latest
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: CLI_ARGS
              value: "--gameid ctf"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 30000
              protocol: UDP
          volumeMounts:
            - name: luanti-data
              mountPath: /config/.minetest
---
apiVersion: v1
kind: Service
metadata:
  name: luanti-data-svc
  namespace: jeux
spec:
  type: LoadBalancer
  ports:
    - name: ""
      port: 30000
      targetPort: 30000
      protocol: UDP
  selector:
    app: luanti
